---
- hosts: "10.2.0.190"
  connection: httpapi

  tasks:
    - name: add-host or delete-host
      cp_mgmt_host:
        color: blue
        name: My GitHub Host
        ip_address: 192.168.191.1
        state: present
        auto_publish_session: true
